export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-12 max-w-2xl mx-auto pb-24 text-[#14162E]">
      <h1 className="text-3xl font-bold mb-2">Terms & Conditions</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: September 2026</p>

      <section className="space-y-6 text-sm leading-relaxed">
        <div>
          <h2 className="font-semibold text-lg mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Sthamly ("the Service"), you agree to be bound by these
            Terms & Conditions. If you do not agree, please do not use the Service.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">2. Description of Service</h2>
          <p>
            Sthamly provides AI visibility auditing for brands and local businesses,
            covering AI model mentions (via third-party AI providers) and Google search
            presence, along with optional paid fixes applied to a connected WordPress
            site or, where available, a Google Business Profile.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">3. Accuracy of Results</h2>
          <p>
            AI visibility scores are generated by querying third-party AI models and
            search APIs at a point in time. Results reflect the knowledge and behavior
            of those external systems and may change without notice, may be incomplete,
            or may not reflect real-time AI Overview behavior. Sthamly does not
            guarantee any specific ranking, mention, or business outcome.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">4. Payments and Refunds</h2>
          <p>
            One-time fixes (₹499) and subscription plans (₹999/month) are processed via
            Razorpay. Once a fix has been successfully applied to your connected
            website, the fee is non-refundable, as the service (code/markup insertion)
            has been delivered. If a payment succeeds but the fix fails to apply due to
            a technical error on our end, contact support for a resolution or refund.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">5. WordPress Connection</h2>
          <p>
            By connecting your WordPress site, you authorize Sthamly to make specific,
            limited changes (schema markup, FAQ content) via the WordPress REST API
            using the application password you provide. You are responsible for the
            accuracy of the credentials you provide and for reviewing changes made to
            your site.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">6. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must provide accurate information when creating an audit or account</li>
            <li>You must not use the Service to audit or target websites you do not own or have authorization to manage, for the purposes of applying fixes</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials</li>
          </ul>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">7. Limitation of Liability</h2>
          <p>
            Sthamly is provided "as is" without warranties of any kind. We are not
            liable for any indirect, incidental, or consequential damages arising from
            use of the Service, including changes in AI visibility, search ranking, or
            business outcomes.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">8. Termination</h2>
          <p>
            We reserve the right to suspend or terminate access to the Service for
            violation of these terms, at our discretion.
          </p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">9. Governing Law</h2>
          <p>These Terms are governed by the laws of India.</p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">10. Changes to Terms</h2>
          <p>We may revise these Terms from time to time. Continued use after changes constitutes acceptance of the revised Terms.</p>
        </div>

        <div>
          <h2 className="font-semibold text-lg mb-2">11. Contact</h2>
          <p>For questions about these Terms, please contact us via the support option in your Account settings.</p>
        </div>
      </section>
    </main>
  );
}