import chromium from '@sparticuz/chromium-min';
import puppeteer from 'puppeteer-core';
import type { Language } from '@/lib/i18n';
import {
  analyzeGaps,
  scoreBand,
  type AuditSnapshot,
  type FixSummary,
  type MentionSummary,
} from '@/lib/reportData';

// User ka diya text (brand name, city, agency) PDF ke HTML mein jaata hai — escape zaroori hai
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function scoreColor(score: number | null): string {
  if (score === null) return '#9CA3AF';
  if (score >= 70) return '#16A34A';
  if (score >= 40) return '#D97706';
  return '#DC2626';
}

// ---------- PDF ke saare fixed (static) labels — English aur Hindi dono ----------
// Naya label add karna ho to bas yahan en/hi dono jodo, aur T(lang).key se use karo.
const STRINGS = {
  en: {
    preparedBy: 'prepared by',
    footerDisclaimer:
      'This report is based on AI model responses at the time of the audit. AI responses can change over time, so the score is a snapshot, not a guarantee.',
    generatedBy: (brand: string) => `Generated by ${brand}`,
    mentioned: 'Mentioned',
    notMentioned: 'Not mentioned',
    unclear: 'Unclear',
    aiModel: 'AI Model',
    result: 'Result',
    sentiment: 'Sentiment',
    sourceLink: 'Source link',
    before: 'Before',
    after: 'After',
    noDataForSection: 'No data available for this section.',
    localAiCheck: (city: string) => `Local AI check (${city})`,
    localAiCheckCompare: 'Local AI check - Before vs After',
    websiteAiCheck: 'Website / brand AI check',
    websiteAiCheckCompare: 'Website / brand AI check - Before vs After',
    googlePresence: 'Google Search Presence',
    googlePresenceCompare: 'Google Search Presence - Before vs After',
    noGoogleData: 'No Google presence data available.',
    check: 'Check',
    knowledgePanel: 'Knowledge Panel / Answer Box',
    appears: 'Appears',
    notShown: 'Not shown',
    organicRank: 'Organic search rank (for a brand-name search)',
    organicRankShort: 'Organic search rank',
    notInTop10: 'Not in top 10',
    aiVisibilityScore: 'AI Visibility Score',
    localMapsScore: 'Local / Maps Score',
    websiteAiScore: 'Website AI Score',
    auditDate: (d: string) => `Audit date: ${d}`,
    reportTypeGap: 'Report type: Gap Report (Before snapshot)',
    gapsHeading: 'Gaps found and what to do',
    noBigGap: 'No major gap found in this audit. Run another audit in 2-4 weeks to maintain the score.',
    whatWasSeen: 'What was seen:',
    whatToDo: 'What to do:',
    nextStep: (brand: string) =>
      `Next step: After fixing the gaps above, run a new audit. ${brand}'s Before/After report treats this audit as the "Before" snapshot and compares it with the new audit, so the real improvement (or lack of it) is clear.`,
    scoreBeforeAfterTitle: 'AI Visibility Score - Before vs After',
    noChange: 'No change',
    points: 'points',
    whatChanged: 'What changed:',
    compareNoData: 'Not enough data was available to compare scores.',
    verdictImproved: 'The scores below are based on the audit\u2019s actual AI responses.',
    verdictNoImprovement:
      'No improvement in scores yet. AI models often take a few weeks to pick up new structured data - try another audit in 2-4 weeks.',
    fixLine: (brand: string, n: number) => `${n} ${brand} fix${n === 1 ? '' : 'es'} were applied during this period.`,
    fixLineNone: (brand: string) =>
      `No paid+applied ${brand} fix was found on record during this period, so any change in score cannot be attributed to a ${brand} fix.`,
    fixesApplied: 'Fixes applied',
    noFixRecord: (brand: string) => `No paid+applied ${brand} fix record was found for this period.`,
    fix: 'Fix',
    site: 'Site',
    appliedOn: 'Applied on',
    remainingGaps: 'Gaps that still remain',
    seScoreImproved: (name: string, b: number, a: number, d: number) =>
      `${name}: ${b} to ${a} (+${d} points) - improvement shown.`,
    seScoreSame: (name: string, b: number) => `${name}: stayed at ${b}.`,
    seScoreDropped: (name: string, b: number, a: number, d: number) =>
      `${name}: ${b} to ${a} (${d} points) - decline seen.`,
    localMapsScoreLabel: 'Local / Maps score',
    websiteAiScoreLabel: 'Website AI score',
    titleGap: 'AI Visibility Gap Report',
    titleBeforeAfter: 'AI Visibility Before/After Report',
  },
  hi: {
    preparedBy: 'तैयार किया',
    footerDisclaimer:
      'यह रिपोर्ट ऑडिट के समय AI मॉडल्स के जवाबों पर आधारित है। AI के जवाब समय के साथ बदल सकते हैं, इसलिए यह स्कोर एक स्नैपशॉट है, गारंटी नहीं।',
    generatedBy: (brand: string) => `${brand} द्वारा तैयार`,
    mentioned: 'पहचाना गया',
    notMentioned: 'नहीं पहचाना',
    unclear: 'स्पष्ट नहीं',
    aiModel: 'AI मॉडल',
    result: 'परिणाम',
    sentiment: 'सेंटिमेंट',
    sourceLink: 'सोर्स लिंक',
    before: 'पहले',
    after: 'बाद में',
    noDataForSection: 'इस सेक्शन का डेटा उपलब्ध नहीं है।',
    localAiCheck: (city: string) => `लोकल AI चेक (${city})`,
    localAiCheckCompare: 'लोकल AI चेक - पहले बनाम बाद में',
    websiteAiCheck: 'वेबसाइट / ब्रांड AI चेक',
    websiteAiCheckCompare: 'वेबसाइट / ब्रांड AI चेक - पहले बनाम बाद में',
    googlePresence: 'Google सर्च प्रेज़ेंस',
    googlePresenceCompare: 'Google सर्च प्रेज़ेंस - पहले बनाम बाद में',
    noGoogleData: 'Google प्रेज़ेंस का डेटा उपलब्ध नहीं है।',
    check: 'चेक',
    knowledgePanel: 'Knowledge Panel / Answer Box',
    appears: 'दिखता है',
    notShown: 'नहीं दिखा',
    organicRank: 'ऑर्गेनिक सर्च रैंक (ब्रांड नाम सर्च पर)',
    organicRankShort: 'ऑर्गेनिक सर्च रैंक',
    notInTop10: 'टॉप 10 में नहीं',
    aiVisibilityScore: 'AI विज़िबिलिटी स्कोर',
    localMapsScore: 'लोकल / मैप्स स्कोर',
    websiteAiScore: 'वेबसाइट AI स्कोर',
    auditDate: (d: string) => `ऑडिट तारीख़: ${d}`,
    reportTypeGap: 'रिपोर्ट टाइप: गैप रिपोर्ट (पहला स्नैपशॉट)',
    gapsHeading: 'आपकी कमियाँ (gaps) और क्या करें',
    noBigGap: 'इस ऑडिट में कोई बड़ा gap नहीं मिला। स्कोर बनाए रखने के लिए 2-4 हफ्तों में दोबारा ऑडिट चलाएं।',
    whatWasSeen: 'क्या दिखा:',
    whatToDo: 'क्या करें:',
    nextStep: (brand: string) =>
      `अगला कदम: ऊपर दी गई कमियों को सुधारने के बाद दोबारा ऑडिट चलाएं। ${brand} की Before/After रिपोर्ट इसी ऑडिट को "Before" मानकर नए ऑडिट से तुलना करती है, ताकि असली सुधार (या सुधार का न होना) साफ़ दिखे।`,
    scoreBeforeAfterTitle: 'AI विज़िबिलिटी स्कोर - पहले बनाम बाद में',
    noChange: 'कोई बदलाव नहीं',
    points: 'अंक',
    whatChanged: 'क्या बदला:',
    compareNoData: 'स्कोर तुलना करने लायक पर्याप्त डेटा उपलब्ध नहीं था।',
    verdictImproved: 'नीचे दिए गए स्कोर ऑडिट के असली AI जवाबों पर आधारित हैं।',
    verdictNoImprovement:
      'अभी तक स्कोर में सुधार नहीं दिखा। AI मॉडल्स को नया structured data पकड़ने में अक्सर कुछ हफ्ते लगते हैं - 2 से 4 हफ्ते बाद दोबारा ऑडिट चलाकर देखें।',
    fixLine: (brand: string, n: number) => `इस दौरान ${n} ${brand} fix अप्लाई हुआ।`,
    fixLineNone: (brand: string) =>
      `इस दौरान कोई paid+applied ${brand} fix रिकॉर्ड में नहीं मिला, इसलिए स्कोर में कोई भी बदलाव ${brand} fix का नतीजा नहीं माना जा सकता।`,
    fixesApplied: 'लगाए गए fix',
    noFixRecord: (brand: string) => `इस अवधि में कोई paid+applied ${brand} fix रिकॉर्ड नहीं मिला।`,
    fix: 'Fix',
    site: 'साइट',
    appliedOn: 'कब लगाया',
    remainingGaps: 'अब भी बाकी कमियाँ',
    seScoreImproved: (name: string, b: number, a: number, d: number) =>
      `${name}: ${b} से ${a} (+${d} अंक) - सुधार दिखा।`,
    seScoreSame: (name: string, b: number) => `${name}: ${b} पर same रहा।`,
    seScoreDropped: (name: string, b: number, a: number, d: number) =>
      `${name}: ${b} से ${a} (${d} अंक) - कमी आई।`,
    localMapsScoreLabel: 'लोकल / मैप्स स्कोर',
    websiteAiScoreLabel: 'वेबसाइट AI स्कोर',
    titleGap: 'AI विज़िबिलिटी गैप रिपोर्ट',
    titleBeforeAfter: 'AI विज़िबिलिटी Before/After रिपोर्ट',
  },
} as const;

function T(lang: Language) {
  return STRINGS[lang] ?? STRINGS.en;
}

const SOURCE_LABELS: Record<string, string> = {
  openai: 'ChatGPT (OpenAI)',
  gemini: 'Gemini (Google)',
  perplexity: 'Perplexity',
  anthropic: 'Claude (Anthropic)',
};

function sourceLabel(source: string): string {
  return SOURCE_LABELS[source] ?? source.charAt(0).toUpperCase() + source.slice(1);
}

// NOTE: PDF mein emoji/special arrows nahi — serverless Chromium mein woh box (tofu) ban jaate hain
// font-family ka Devanagari fallback sirf Hindi PDF ke liye jodte hain (buildCss mein) — isse
// English PDF ka font-stack bilkul pehle jaisa (untouched) rehta hai.
function buildCss(lang: Language): string {
  const bodyFont =
    lang === 'hi'
      ? `'Noto Sans Devanagari', 'Helvetica Neue', Arial, sans-serif`
      : `'Helvetica Neue', Arial, sans-serif`;
  return `
  * { box-sizing: border-box; }
  body { font-family: ${bodyFont}; color: #14162E; margin: 0; padding: 40px 50px; font-size: 13px; }
  .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #8B85E3; padding-bottom: 16px; margin-bottom: 26px; }
  .header h1 { color: #E0A44B; margin: 0; font-size: 26px; }
  .header .tag { font-size: 12px; color: #666; }
  .brand-title { font-size: 22px; font-weight: bold; margin: 0 0 2px 0; }
  .brand-sub { color: #666; margin: 0 0 6px 0; font-size: 13px; }
  .date-row { display: flex; justify-content: space-between; font-size: 11px; color: #888; margin-top: 4px; }
  .section-title { font-size: 15px; font-weight: bold; margin: 28px 0 12px 0; border-left: 4px solid #8B85E3; padding-left: 10px; }
  .scores-grid { display: flex; gap: 20px; }
  .score-block { flex: 1; text-align: center; background: #FAFAFC; border-radius: 12px; padding: 16px; }
  .score-label { font-size: 12px; color: #666; margin: 0 0 10px 0; font-weight: 600; }
  .score-row { display: flex; align-items: center; justify-content: center; gap: 12px; }
  .score-circle { width: 70px; height: 70px; border-radius: 50%; border: 5px solid; display: flex; align-items: center; justify-content: center; font-size: 22px; font-weight: bold; }
  .band { margin-top: 8px; font-size: 12px; font-weight: bold; }
  .arrow { width: 22px; height: 2px; background: #8B85E3; position: relative; }
  .arrow:after { content: ''; position: absolute; right: -1px; top: -4px; border-left: 8px solid #8B85E3; border-top: 5px solid transparent; border-bottom: 5px solid transparent; }
  .diff { margin: 8px 0 0 0; font-weight: bold; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin-top: 6px; font-size: 12.5px; }
  th, td { border: 1px solid #E5E5EA; padding: 8px 10px; text-align: center; }
  td.left, th.left { text-align: left; }
  th { background: #14162E; color: white; font-size: 11px; }
  .badge { padding: 3px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; display: inline-block; }
  .badge.green { background: #DCFCE7; color: #16A34A; }
  .badge.red { background: #FEE2E2; color: #DC2626; }
  .badge.gray { background: #F3F4F6; color: #6B7280; }
  .badge.amber { background: #FEF3C7; color: #B45309; }
  .summary-box { background: #F7F5FF; border-left: 4px solid #8B85E3; border-radius: 8px; padding: 14px 18px; margin-top: 22px; font-size: 13px; line-height: 1.6; }
  .gap { border: 1px solid #E5E5EA; border-radius: 10px; padding: 12px 14px; margin-bottom: 10px; page-break-inside: avoid; }
  .gap-head { display: flex; gap: 8px; align-items: center; margin-bottom: 6px; }
  .gap-title { font-weight: bold; font-size: 13px; }
  .gap p { margin: 3px 0; line-height: 1.5; }
  .gap .lbl { font-weight: bold; color: #555; }
  .muted { color: #6B7280; font-size: 12px; line-height: 1.5; }
  ul { margin: 6px 0 0 18px; padding: 0; line-height: 1.6; }
  .footer { margin-top: 34px; padding-top: 12px; border-top: 1px solid #eee; font-size: 10px; color: #999; text-align: center; line-height: 1.5; }
`;
}

// White-label logic: agencyName diya ho to PDF ka main brand wahi bane (Sthamly nahi dikhta).
// agencyName khali ho to default apna "Sthamly" brand dikhta hai — jaisa pehle tha.
function pageShell(title: string, agencyName: string | undefined, body: string, lang: Language): string {
  const t = T(lang);
  const hasAgency = !!agencyName && agencyName.trim().length > 0;
  const headerBrand = hasAgency ? esc(agencyName) : 'Sthamly';
  const footerLine = hasAgency ? '' : `${t.generatedBy('Sthamly')} &middot; sthamly.com<br>`;
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
<style>${buildCss(lang)}</style>
</head>
<body>
  <div class="header">
    <h1>${headerBrand}</h1>
    <div class="tag">${esc(title)}</div>
  </div>
  ${body}
  <div class="footer">
    ${footerLine}${t.footerDisclaimer}
  </div>
</body>
</html>`;
}

function badge(t: ReturnType<typeof T>, m?: MentionSummary): string {
  if (!m) return '<span class="badge gray">-</span>';
  if (m.mentioned === true) return `<span class="badge green">${t.mentioned}</span>`;
  if (m.mentioned === false) return `<span class="badge red">${t.notMentioned}</span>`;
  return `<span class="badge gray">${t.unclear}</span>`;
}

function singleScoreBlock(label: string, score: number | null, lang: Language): string {
  return `
    <div class="score-block">
      <p class="score-label">${esc(label)}</p>
      <div class="score-row">
        <div class="score-circle" style="border-color:${scoreColor(score)}"><span>${score ?? '-'}</span></div>
      </div>
      <p class="band" style="color:${scoreColor(score)}">${scoreBand(score, lang)}</p>
    </div>`;
}

function compareScoreBlock(label: string, before: number | null, after: number | null, lang: Language): string {
  const t = T(lang);
  const diff = before !== null && after !== null ? after - before : null;
  const diffLabel = diff === null ? '' : diff > 0 ? `+${diff} ${t.points}` : diff === 0 ? t.noChange : `${diff} ${t.points}`;
  const diffColor = diff === null ? '#6B7280' : diff > 0 ? '#16A34A' : diff === 0 ? '#6B7280' : '#DC2626';
  return `
    <div class="score-block">
      <p class="score-label">${esc(label)}</p>
      <div class="score-row">
        <div class="score-circle" style="border-color:${scoreColor(before)}"><span>${before ?? '-'}</span></div>
        <div class="arrow"></div>
        <div class="score-circle" style="border-color:${scoreColor(after)}"><span>${after ?? '-'}</span></div>
      </div>
      ${diff !== null ? `<p class="diff" style="color:${diffColor}">${diffLabel}</p>` : ''}
    </div>`;
}

function sentimentLabel(m: MentionSummary): string {
  if (m.mentioned !== true) return '-';
  return m.sentiment ? m.sentiment.charAt(0).toUpperCase() + m.sentiment.slice(1) : '-';
}

function singleMentionTable(t: ReturnType<typeof T>, list: MentionSummary[], showCitation: boolean): string {
  if (list.length === 0) return `<p class="muted">${t.noDataForSection}</p>`;
  const rows = list
    .map(
      (m) => `
      <tr>
        <td class="left">${esc(sourceLabel(m.source))}</td>
        <td>${badge(t, m)}</td>
        <td>${esc(sentimentLabel(m))}</td>
        ${showCitation ? `<td class="left">${m.citationUrl ? esc(m.citationUrl) : '-'}</td>` : ''}
      </tr>`
    )
    .join('');
  return `<table>
    <tr><th class="left">${t.aiModel}</th><th>${t.result}</th><th>${t.sentiment}</th>${showCitation ? `<th class="left">${t.sourceLink}</th>` : ''}</tr>
    ${rows}
  </table>`;
}

function compareMentionTable(t: ReturnType<typeof T>, before: MentionSummary[], after: MentionSummary[]): string {
  const sources = Array.from(new Set([...before.map((m) => m.source), ...after.map((m) => m.source)]));
  if (sources.length === 0) return `<p class="muted">${t.noDataForSection}</p>`;
  const rows = sources
    .map((source) => {
      const b = before.find((m) => m.source === source);
      const a = after.find((m) => m.source === source);
      return `<tr><td class="left">${esc(sourceLabel(source))}</td><td>${badge(t, b)}</td><td>${badge(t, a)}</td></tr>`;
    })
    .join('');
  return `<table>
    <tr><th class="left">${t.aiModel}</th><th>${t.before}</th><th>${t.after}</th></tr>
    ${rows}
  </table>`;
}

function googleRow(t: ReturnType<typeof T>, s: AuditSnapshot): string {
  if (!s.google) return `<p class="muted">${t.noGoogleData}</p>`;
  return `<table>
    <tr><th class="left">${t.check}</th><th>${t.result}</th></tr>
    <tr><td class="left">${t.knowledgePanel}</td><td>${
      s.google.appearsInOverview ? `<span class="badge green">${t.appears}</span>` : `<span class="badge red">${t.notShown}</span>`
    }</td></tr>
    <tr><td class="left">${t.organicRank}</td><td>${
      s.google.rankedPosition !== null
        ? `<span class="badge green">#${s.google.rankedPosition}</span>`
        : `<span class="badge red">${t.notInTop10}</span>`
    }</td></tr>
  </table>`;
}

function googleCompare(t: ReturnType<typeof T>, before: AuditSnapshot, after: AuditSnapshot): string {
  if (!before.google && !after.google) return '';
  const panel = (s: AuditSnapshot) =>
    !s.google
      ? '<span class="badge gray">-</span>'
      : s.google.appearsInOverview
      ? `<span class="badge green">${t.appears}</span>`
      : `<span class="badge red">${t.notShown}</span>`;
  const rank = (s: AuditSnapshot) =>
    !s.google
      ? '<span class="badge gray">-</span>'
      : s.google.rankedPosition !== null
      ? `<span class="badge green">#${s.google.rankedPosition}</span>`
      : `<span class="badge red">${t.notInTop10}</span>`;
  return `
    <div class="section-title">${t.googlePresenceCompare}</div>
    <table>
      <tr><th class="left">${t.check}</th><th>${t.before}</th><th>${t.after}</th></tr>
      <tr><td class="left">${t.knowledgePanel}</td><td>${panel(before)}</td><td>${panel(after)}</td></tr>
      <tr><td class="left">${t.organicRankShort}</td><td>${rank(before)}</td><td>${rank(after)}</td></tr>
    </table>`;
}

function gapCards(t: ReturnType<typeof T>, s: AuditSnapshot, lang: Language, limit?: number): string {
  const gaps = analyzeGaps(s, lang);
  if (gaps.length === 0) {
    return `<p class="muted">${t.noBigGap}</p>`;
  }
  const list = typeof limit === 'number' ? gaps.slice(0, limit) : gaps;
  return list
    .map((g, i) => {
      const cls = g.severity === 'high' ? 'red' : g.severity === 'medium' ? 'amber' : 'gray';
      const txt = g.severity === 'high' ? 'HIGH' : g.severity === 'medium' ? 'MEDIUM' : 'LOW';
      return `
      <div class="gap">
        <div class="gap-head"><span class="badge ${cls}">${txt}</span><span class="gap-title">${i + 1}. ${esc(g.title)}</span></div>
        <p><span class="lbl">${t.whatWasSeen}</span> ${esc(g.detail)}</p>
        <p><span class="lbl">${t.whatToDo}</span> ${esc(g.action)}</p>
      </div>`;
    })
    .join('');
}

// ---------- 1) PEHLE AUDIT KA "KAMIYON" WALA REPORT ----------
export function buildGapReportHtml(s: AuditSnapshot, agencyName?: string, lang: Language = 'en'): string {
  const t = T(lang);
  const local = s.mentions.filter((m) => m.isLocal);
  const web = s.mentions.filter((m) => !m.isLocal);
  const brandForCopy = agencyName && agencyName.trim() ? agencyName.trim() : 'Sthamly';

  const body = `
    <p class="brand-title">${esc(s.brandName)}</p>
    <p class="brand-sub">${esc(s.city)}${s.websiteUrl ? ` &middot; ${esc(s.websiteUrl)}` : ''}</p>
    <div class="date-row"><span>${t.auditDate(s.date)}</span><span>${t.reportTypeGap}</span></div>

    <div class="section-title">${t.aiVisibilityScore}</div>
    <div class="scores-grid">
      ${singleScoreBlock(t.localMapsScore, s.localScore, lang)}
      ${s.hasWebsite ? singleScoreBlock(t.websiteAiScore, s.websiteScore, lang) : ''}
    </div>

    <div class="section-title">${t.localAiCheck(s.city)}</div>
    ${singleMentionTable(t, local, false)}

    ${
      s.hasWebsite
        ? `<div class="section-title">${t.websiteAiCheck}</div>
           ${singleMentionTable(t, web, true)}
           <div class="section-title">${t.googlePresence}</div>
           ${googleRow(t, s)}`
        : ''
    }

    <div class="section-title">${t.gapsHeading}</div>
    ${gapCards(t, s, lang)}

    <div class="summary-box">
      <b>${t.whatChanged.replace(':', '')}:</b> ${t.nextStep(brandForCopy)}
    </div>`;

  return pageShell(t.titleGap, agencyName, body, lang);
}

// ---------- 2) FIX KE BAAD BEFORE / AFTER REPORT ----------
function changeSummary(
  t: ReturnType<typeof T>,
  before: AuditSnapshot,
  after: AuditSnapshot,
  fixes: FixSummary[],
  agencyName: string | undefined
): string {
  const brandForCopy = agencyName && agencyName.trim() ? agencyName.trim() : 'Sthamly';
  const pairs: { name: string; b: number | null; a: number | null }[] = [
    { name: t.localMapsScoreLabel, b: before.localScore, a: after.localScore },
  ];
  if (before.hasWebsite || after.hasWebsite) {
    pairs.push({ name: t.websiteAiScoreLabel, b: before.websiteScore, a: after.websiteScore });
  }
  const comparable = pairs.filter((p) => p.b !== null && p.a !== null);

  const lines = comparable.map((p) => {
    const b = p.b as number;
    const a = p.a as number;
    const d = a - b;
    if (d > 0) return t.seScoreImproved(esc(p.name), b, a, d);
    if (d === 0) return t.seScoreSame(esc(p.name), b);
    return t.seScoreDropped(esc(p.name), b, a, d);
  });

  const anyImproved = comparable.some((p) => (p.a as number) > (p.b as number));
  let verdict: string;
  if (comparable.length === 0) {
    verdict = t.compareNoData;
  } else if (anyImproved) {
    verdict = t.verdictImproved;
  } else {
    verdict = t.verdictNoImprovement;
  }

  const fixLine = fixes.length > 0 ? t.fixLine(brandForCopy, fixes.length) : t.fixLineNone(brandForCopy);

  return `<div class="summary-box"><b>${t.whatChanged}</b><br>${lines.join('<br>')}${lines.length ? '<br>' : ''}${esc(verdict)}<br>${esc(fixLine)}</div>`;
}

export function buildReportHtml(
  before: AuditSnapshot,
  after: AuditSnapshot,
  agencyName?: string,
  fixes: FixSummary[] = [],
  lang: Language = 'en'
): string {
  const t = T(lang);
  const bLocal = before.mentions.filter((m) => m.isLocal);
  const aLocal = after.mentions.filter((m) => m.isLocal);
  const bWeb = before.mentions.filter((m) => !m.isLocal);
  const aWeb = after.mentions.filter((m) => !m.isLocal);
  const showWebsite = before.hasWebsite || after.hasWebsite;
  const brandForCopy = agencyName && agencyName.trim() ? agencyName.trim() : 'Sthamly';

  const fixesHtml =
    fixes.length > 0
      ? `<table>
          <tr><th class="left">${t.fix}</th><th class="left">${t.site}</th><th>${t.appliedOn}</th></tr>
          ${fixes
            .map(
              (f) =>
                `<tr><td class="left">${esc(f.label)}</td><td class="left">${esc(f.site ?? '-')}</td><td>${esc(f.appliedAt)}</td></tr>`
            )
            .join('')}
        </table>`
      : `<p class="muted">${t.noFixRecord(brandForCopy)}</p>`;

  const body = `
    <p class="brand-title">${esc(before.brandName)}</p>
    <p class="brand-sub">${esc(before.city)}${before.websiteUrl ? ` &middot; ${esc(before.websiteUrl)}` : ''}</p>
    <div class="date-row"><span>${t.before}: ${esc(before.date)}</span><span>${t.after}: ${esc(after.date)}</span></div>

    <div class="section-title">${t.scoreBeforeAfterTitle}</div>
    <div class="scores-grid">
      ${compareScoreBlock(t.localMapsScore, before.localScore, after.localScore, lang)}
      ${showWebsite ? compareScoreBlock(t.websiteAiScore, before.websiteScore, after.websiteScore, lang) : ''}
    </div>

    ${changeSummary(t, before, after, fixes, agencyName)}

    <div class="section-title">${t.fixesApplied}</div>
    ${fixesHtml}

    <div class="section-title">${t.localAiCheckCompare}</div>
    ${compareMentionTable(t, bLocal, aLocal)}

    ${
      showWebsite
        ? `<div class="section-title">${t.websiteAiCheckCompare}</div>
           ${compareMentionTable(t, bWeb, aWeb)}
           ${googleCompare(t, before, after)}`
        : ''
    }

    <div class="section-title">${t.remainingGaps}</div>
    ${gapCards(t, after, lang, 5)}`;

  return pageShell(t.titleBeforeAfter, agencyName, body, lang);
}

// @sparticuz/chromium-min khud Chromium binary include nahi karta (isiliye chhota hai
// aur Vercel ke function-size limit mein aasani se fit hota hai). Pehli call par ye
// URL se pack.tar download karke /tmp mein extract karta hai; baad ki (warm) calls
// isi cached copy ko reuse karti hain. Version yahan aur package.json mein SAME rakho.
const CHROMIUM_PACK_URL =
  process.env.CHROMIUM_PACK_URL ||
  'https://github.com/Sparticuz/chromium/releases/download/v138.0.2/chromium-v138.0.2-pack.x64.tar';

// Hindi (Devanagari) text render karne ke liye serverless Chromium mein by-default koi
// Devanagari font nahi hota — usko load nahi kiya to PDF mein Hindi text khaali boxes
// (tofu) ban jaata hai. Isliye Hindi report ke liye ek baar yeh font load karte hain.
// (jsDelivr CDN Vercel ke serverless network se reliably reach nahi ho raha tha, isliye
// GitHub ka apna raw file host (raw.githubusercontent.com) use kar rahe hain — zyada stable.)
const DEVANAGARI_FONT_URL =
  'https://raw.githubusercontent.com/notofonts/notofonts.github.io/main/fonts/NotoSansDevanagari/hinted/ttf/NotoSansDevanagari-Regular.ttf';

let devanagariFontLoaded = false;

// ---------- PDF banane wala ----------
// Har step alag se try/catch + log karte hain taaki Vercel Function Logs mein
// saaf pata chale ki crash kahan hua (chromium path, launch, ya PDF render).
export async function generatePdfBuffer(html: string, lang: Language = 'en'): Promise<Uint8Array> {
  if (lang === 'hi' && !devanagariFontLoaded) {
    try {
      await chromium.font(DEVANAGARI_FONT_URL);
      devanagariFontLoaded = true;
      console.log('[pdf] Devanagari font loaded');
    } catch (e) {
      // Font load fail ho bhi jaaye to PDF banna nahi rukna chahiye — sirf Hindi text
      // thoda kam polished dikhega (fallback font).
      console.error('[pdf] Devanagari font load failed (continuing without it):', e);
    }
  }

  let executablePath: string;
  try {
    // PDF ke liye WebGL/graphics stack ki zaroorat nahi — isse off rakhne se
    // launch zyada stable rehta hai serverless (AL2023) environment mein.
    chromium.setGraphicsMode = false;
    executablePath = await chromium.executablePath(CHROMIUM_PACK_URL);
    console.log('[pdf] chromium executablePath:', executablePath);
  } catch (e) {
    console.error('[pdf] chromium.executablePath() failed:', e);
    throw new Error('Chromium binary nahi mil payi (executablePath failed)');
  }

  let browser: any;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath,
      headless: true,
    });
    console.log('[pdf] browser launched');
  } catch (e) {
    console.error('[pdf] puppeteer.launch() failed:', e);
    throw new Error(`Chromium launch nahi ho paya: ${e instanceof Error ? e.message : String(e)}`);
  }

  try {
    const page = await browser.newPage();
    // HTML mein koi script/external resource nahi chahiye — JS band rakhna safe hai
    await page.setJavaScriptEnabled(false);
    await page.setContent(html, { waitUntil: 'load' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' },
    });
    console.log('[pdf] pdf rendered, bytes:', pdf.length);
    return new Uint8Array(pdf);
  } catch (e) {
    console.error('[pdf] page render/pdf failed:', e);
    throw new Error(`PDF render nahi ho paya: ${e instanceof Error ? e.message : String(e)}`);
  } finally {
    try {
      await browser.close();
    } catch {
      /* ignore close errors */
    }
  }
}
