import chromium from '@sparticuz/chromium-min';
import puppeteer from 'puppeteer-core';
import {
  analyzeGaps,
  scoreBand,
  type AuditSnapshot,
  type FixSummary,
  type MentionSummary,
} from '@/lib/reportData';

// User ka diya text (brand name, city, agency) PDF ke HTML mein jaata hai — escape zaroori hai
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function scoreColor(score: number | null): string {
  if (score === null) return '#9CA3AF';
  if (score >= 70) return '#16A34A';
  if (score >= 40) return '#D97706';
  return '#DC2626';
}

const SOURCE_LABELS: Record<string, string> = {
  openai: 'ChatGPT (OpenAI)',
  gemini: 'Gemini (Google)',
  perplexity: 'Perplexity',
  anthropic: 'Claude (Anthropic)',
};

function sourceLabel(source: string): string {
  return SOURCE_LABELS[source] ?? source.charAt(0).toUpperCase() + source.slice(1);
}

// NOTE: PDF mein emoji/special arrows nahi — serverless Chromium mein woh box (tofu) ban jaate hain
const BASE_CSS = `
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #14162E; margin: 0; padding: 40px 50px; font-size: 13px; }
  .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #8B85E3; padding-bottom: 16px; margin-bottom: 26px; }
  .header h1 { color: #E0A44B; margin: 0; font-size: 26px; }
  .header .tag { font-size: 12px; color: #666; }
  .brand-title { font-size: 22px; font-weight: bold; margin: 0 0 2px 0; }
  .brand-sub { color: #666; margin: 0 0 6px 0; font-size: 13px; }
  .date-row { display: flex; justify-content: space-between; font-size: 11px; color: #888; margin-top: 4px; }
  .section-title { font-size: 15px; font-weight: bold; margin: 28px 0 12px 0; border-left: 4px solid #8B85E3; padding-left: 10px; }
  .scores-grid { display: flex; gap: 20px; }
  .score-block { flex: 1; text-align: center; background: #FAFAFC; border-radius: 12px; padding: 16px; }
  .score-label { font-size: 12px; color: #666; margin: 0 0 10px 0; font-weight: 600; }
  .score-row { display: flex; align-items: center; justify-content: center; gap: 12px; }
  .score-circle { width: 70px; height: 70px; border-radius: 50%; border: 5px solid; display: flex; align-items: center; justify-content: center; font-size: 22px; font-weight: bold; }
  .band { margin-top: 8px; font-size: 12px; font-weight: bold; }
  .arrow { width: 22px; height: 2px; background: #8B85E3; position: relative; }
  .arrow:after { content: ''; position: absolute; right: -1px; top: -4px; border-left: 8px solid #8B85E3; border-top: 5px solid transparent; border-bottom: 5px solid transparent; }
  .diff { margin: 8px 0 0 0; font-weight: bold; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin-top: 6px; font-size: 12.5px; }
  th, td { border: 1px solid #E5E5EA; padding: 8px 10px; text-align: center; }
  td.left, th.left { text-align: left; }
  th { background: #14162E; color: white; font-size: 11px; }
  .badge { padding: 3px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; display: inline-block; }
  .badge.green { background: #DCFCE7; color: #16A34A; }
  .badge.red { background: #FEE2E2; color: #DC2626; }
  .badge.gray { background: #F3F4F6; color: #6B7280; }
  .badge.amber { background: #FEF3C7; color: #B45309; }
  .summary-box { background: #F7F5FF; border-left: 4px solid #8B85E3; border-radius: 8px; padding: 14px 18px; margin-top: 22px; font-size: 13px; line-height: 1.6; }
  .gap { border: 1px solid #E5E5EA; border-radius: 10px; padding: 12px 14px; margin-bottom: 10px; page-break-inside: avoid; }
  .gap-head { display: flex; gap: 8px; align-items: center; margin-bottom: 6px; }
  .gap-title { font-weight: bold; font-size: 13px; }
  .gap p { margin: 3px 0; line-height: 1.5; }
  .gap .lbl { font-weight: bold; color: #555; }
  .muted { color: #6B7280; font-size: 12px; line-height: 1.5; }
  ul { margin: 6px 0 0 18px; padding: 0; line-height: 1.6; }
  .footer { margin-top: 34px; padding-top: 12px; border-top: 1px solid #eee; font-size: 10px; color: #999; text-align: center; line-height: 1.5; }
`;

function pageShell(title: string, agencyName: string | undefined, body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
<style>${BASE_CSS}</style>
</head>
<body>
  <div class="header">
    <h1>Sthamly</h1>
    <div class="tag">${esc(title)}${agencyName ? ` &middot; prepared by ${esc(agencyName)}` : ''}</div>
  </div>
  ${body}
  <div class="footer">
    Generated by Sthamly &middot; sthamly.com<br>
    Yeh report audit ke waqt AI models ke jawab par based hai. AI ke jawab samay ke saath badal sakte hain,
    isliye score ek snapshot hai, guarantee nahi.
  </div>
</body>
</html>`;
}

function badge(m?: MentionSummary): string {
  if (!m) return '<span class="badge gray">-</span>';
  if (m.mentioned === true) return '<span class="badge green">Mentioned</span>';
  if (m.mentioned === false) return '<span class="badge red">Not mentioned</span>';
  return '<span class="badge gray">Unclear</span>';
}

function singleScoreBlock(label: string, score: number | null): string {
  return `
    <div class="score-block">
      <p class="score-label">${esc(label)}</p>
      <div class="score-row">
        <div class="score-circle" style="border-color:${scoreColor(score)}"><span>${score ?? '-'}</span></div>
      </div>
      <p class="band" style="color:${scoreColor(score)}">${scoreBand(score)}</p>
    </div>`;
}

function compareScoreBlock(label: string, before: number | null, after: number | null): string {
  const diff = before !== null && after !== null ? after - before : null;
  const diffLabel = diff === null ? '' : diff > 0 ? `+${diff} points` : diff === 0 ? 'No change' : `${diff} points`;
  const diffColor = diff === null ? '#6B7280' : diff > 0 ? '#16A34A' : diff === 0 ? '#6B7280' : '#DC2626';
  return `
    <div class="score-block">
      <p class="score-label">${esc(label)}</p>
      <div class="score-row">
        <div class="score-circle" style="border-color:${scoreColor(before)}"><span>${before ?? '-'}</span></div>
        <div class="arrow"></div>
        <div class="score-circle" style="border-color:${scoreColor(after)}"><span>${after ?? '-'}</span></div>
      </div>
      ${diff !== null ? `<p class="diff" style="color:${diffColor}">${diffLabel}</p>` : ''}
    </div>`;
}

function sentimentLabel(m: MentionSummary): string {
  if (m.mentioned !== true) return '-';
  return m.sentiment ? m.sentiment.charAt(0).toUpperCase() + m.sentiment.slice(1) : '-';
}

function singleMentionTable(list: MentionSummary[], showCitation: boolean): string {
  if (list.length === 0) return '<p class="muted">Is section ka data available nahi hai.</p>';
  const rows = list
    .map(
      (m) => `
      <tr>
        <td class="left">${esc(sourceLabel(m.source))}</td>
        <td>${badge(m)}</td>
        <td>${esc(sentimentLabel(m))}</td>
        ${showCitation ? `<td class="left">${m.citationUrl ? esc(m.citationUrl) : '-'}</td>` : ''}
      </tr>`
    )
    .join('');
  return `<table>
    <tr><th class="left">AI Model</th><th>Result</th><th>Sentiment</th>${showCitation ? '<th class="left">Source link</th>' : ''}</tr>
    ${rows}
  </table>`;
}

function compareMentionTable(before: MentionSummary[], after: MentionSummary[]): string {
  const sources = Array.from(new Set([...before.map((m) => m.source), ...after.map((m) => m.source)]));
  if (sources.length === 0) return '<p class="muted">Is section ka data available nahi hai.</p>';
  const rows = sources
    .map((source) => {
      const b = before.find((m) => m.source === source);
      const a = after.find((m) => m.source === source);
      return `<tr><td class="left">${esc(sourceLabel(source))}</td><td>${badge(b)}</td><td>${badge(a)}</td></tr>`;
    })
    .join('');
  return `<table>
    <tr><th class="left">AI Model</th><th>Before</th><th>After</th></tr>
    ${rows}
  </table>`;
}

function googleRow(s: AuditSnapshot): string {
  if (!s.google) return '<p class="muted">Google presence ka data available nahi hai.</p>';
  return `<table>
    <tr><th class="left">Check</th><th>Result</th></tr>
    <tr><td class="left">Knowledge Panel / Answer Box</td><td>${
      s.google.appearsInOverview ? '<span class="badge green">Appears</span>' : '<span class="badge red">Not shown</span>'
    }</td></tr>
    <tr><td class="left">Organic search rank (brand naam search par)</td><td>${
      s.google.rankedPosition !== null
        ? `<span class="badge green">#${s.google.rankedPosition}</span>`
        : '<span class="badge red">Not in top 10</span>'
    }</td></tr>
  </table>`;
}

function googleCompare(before: AuditSnapshot, after: AuditSnapshot): string {
  if (!before.google && !after.google) return '';
  const panel = (s: AuditSnapshot) =>
    !s.google
      ? '<span class="badge gray">-</span>'
      : s.google.appearsInOverview
      ? '<span class="badge green">Appears</span>'
      : '<span class="badge red">Not shown</span>';
  const rank = (s: AuditSnapshot) =>
    !s.google
      ? '<span class="badge gray">-</span>'
      : s.google.rankedPosition !== null
      ? `<span class="badge green">#${s.google.rankedPosition}</span>`
      : '<span class="badge red">Not in top 10</span>';
  return `
    <div class="section-title">Google Search Presence - Before vs After</div>
    <table>
      <tr><th class="left">Check</th><th>Before</th><th>After</th></tr>
      <tr><td class="left">Knowledge Panel / Answer Box</td><td>${panel(before)}</td><td>${panel(after)}</td></tr>
      <tr><td class="left">Organic search rank</td><td>${rank(before)}</td><td>${rank(after)}</td></tr>
    </table>`;
}

function gapCards(s: AuditSnapshot, limit?: number): string {
  const gaps = analyzeGaps(s);
  if (gaps.length === 0) {
    return '<p class="muted">Is audit mein koi bada gap nahi mila. Score ko banaye rakhne ke liye 2-4 hafte mein dobara audit chalayein.</p>';
  }
  const list = typeof limit === 'number' ? gaps.slice(0, limit) : gaps;
  return list
    .map((g, i) => {
      const cls = g.severity === 'high' ? 'red' : g.severity === 'medium' ? 'amber' : 'gray';
      const txt = g.severity === 'high' ? 'HIGH' : g.severity === 'medium' ? 'MEDIUM' : 'LOW';
      return `
      <div class="gap">
        <div class="gap-head"><span class="badge ${cls}">${txt}</span><span class="gap-title">${i + 1}. ${esc(g.title)}</span></div>
        <p><span class="lbl">Kya dikha:</span> ${esc(g.detail)}</p>
        <p><span class="lbl">Kya karein:</span> ${esc(g.action)}</p>
      </div>`;
    })
    .join('');
}

// ---------- 1) PEHLE AUDIT KA "KAMIYON" WALA REPORT ----------
export function buildGapReportHtml(s: AuditSnapshot, agencyName?: string): string {
  const local = s.mentions.filter((m) => m.isLocal);
  const web = s.mentions.filter((m) => !m.isLocal);

  const body = `
    <p class="brand-title">${esc(s.brandName)}</p>
    <p class="brand-sub">${esc(s.city)}${s.websiteUrl ? ` &middot; ${esc(s.websiteUrl)}` : ''}</p>
    <div class="date-row"><span>Audit date: ${esc(s.date)}</span><span>Report type: Gap Report (Before snapshot)</span></div>

    <div class="section-title">AI Visibility Score</div>
    <div class="scores-grid">
      ${singleScoreBlock('Local / Maps Score', s.localScore)}
      ${s.hasWebsite ? singleScoreBlock('Website AI Score', s.websiteScore) : ''}
    </div>

    <div class="section-title">Local AI check (${esc(s.city)})</div>
    ${singleMentionTable(local, false)}

    ${
      s.hasWebsite
        ? `<div class="section-title">Website / brand AI check</div>
           ${singleMentionTable(web, true)}
           <div class="section-title">Google Search Presence</div>
           ${googleRow(s)}`
        : ''
    }

    <div class="section-title">Aapki kamiyan (gaps) aur kya karein</div>
    ${gapCards(s)}

    <div class="summary-box">
      <b>Agla kadam:</b> Upar diye gaye gaps ko sudharne ke baad dobara audit chalayein. Sthamly ka
      Before/After report isi audit ko "Before" maan kar naye audit se compare karta hai, taaki asli
      sudhaar (ya sudhaar ka na hona) saaf dikhe.
    </div>`;

  return pageShell('AI Visibility Gap Report', agencyName, body);
}

// ---------- 2) FIX KE BAAD BEFORE / AFTER REPORT ----------
function changeSummary(before: AuditSnapshot, after: AuditSnapshot, fixes: FixSummary[]): string {
  const pairs: { name: string; b: number | null; a: number | null }[] = [
    { name: 'Local / Maps score', b: before.localScore, a: after.localScore },
  ];
  if (before.hasWebsite || after.hasWebsite) {
    pairs.push({ name: 'Website AI score', b: before.websiteScore, a: after.websiteScore });
  }
  const comparable = pairs.filter((p) => p.b !== null && p.a !== null);

  const lines = comparable.map((p) => {
    const d = (p.a as number) - (p.b as number);
    if (d > 0) return `${esc(p.name)}: ${p.b} se ${p.a} (+${d} points) - sudhaar dikha.`;
    if (d === 0) return `${esc(p.name)}: ${p.b} par same raha.`;
    return `${esc(p.name)}: ${p.b} se ${p.a} (${d} points) - kami aayi.`;
  });

  const anyImproved = comparable.some((p) => (p.a as number) > (p.b as number));
  let verdict: string;
  if (comparable.length === 0) {
    verdict = 'Score compare karne layak data available nahi tha.';
  } else if (anyImproved) {
    verdict = 'Neeche diye scores audit ke asli AI jawab par based hain.';
  } else {
    verdict =
      'Abhi tak scores mein sudhaar nahi dikha. AI models ko naye structured data ko pick karne mein aksar kuch hafte lagte hain - 2 se 4 hafte baad dobara audit chalakar dekhein.';
  }

  const fixLine =
    fixes.length > 0
      ? `Is dauran ${fixes.length} Sthamly fix apply hua.`
      : 'Is dauran koi Sthamly auto-fix apply hota record mein nahi mila, isliye score mein koi bhi badlav Sthamly fix ka nateeja nahi maana ja sakta.';

  return `<div class="summary-box"><b>Kya badla:</b><br>${lines.join('<br>')}${lines.length ? '<br>' : ''}${esc(verdict)}<br>${esc(fixLine)}</div>`;
}

export function buildReportHtml(
  before: AuditSnapshot,
  after: AuditSnapshot,
  agencyName?: string,
  fixes: FixSummary[] = []
): string {
  const bLocal = before.mentions.filter((m) => m.isLocal);
  const aLocal = after.mentions.filter((m) => m.isLocal);
  const bWeb = before.mentions.filter((m) => !m.isLocal);
  const aWeb = after.mentions.filter((m) => !m.isLocal);
  const showWebsite = before.hasWebsite || after.hasWebsite;

  const fixesHtml =
    fixes.length > 0
      ? `<table>
          <tr><th class="left">Fix</th><th class="left">Site</th><th>Applied on</th></tr>
          ${fixes
            .map(
              (f) =>
                `<tr><td class="left">${esc(f.label)}</td><td class="left">${esc(f.site ?? '-')}</td><td>${esc(f.appliedAt)}</td></tr>`
            )
            .join('')}
        </table>`
      : '<p class="muted">Is period mein koi paid+applied Sthamly fix record nahi mila.</p>';

  const body = `
    <p class="brand-title">${esc(before.brandName)}</p>
    <p class="brand-sub">${esc(before.city)}${before.websiteUrl ? ` &middot; ${esc(before.websiteUrl)}` : ''}</p>
    <div class="date-row"><span>Before: ${esc(before.date)}</span><span>After: ${esc(after.date)}</span></div>

    <div class="section-title">AI Visibility Score - Before vs After</div>
    <div class="scores-grid">
      ${compareScoreBlock('Local / Maps Score', before.localScore, after.localScore)}
      ${showWebsite ? compareScoreBlock('Website AI Score', before.websiteScore, after.websiteScore) : ''}
    </div>

    ${changeSummary(before, after, fixes)}

    <div class="section-title">Fix jo apply hua</div>
    ${fixesHtml}

    <div class="section-title">Local AI check - Before vs After</div>
    ${compareMentionTable(bLocal, aLocal)}

    ${
      showWebsite
        ? `<div class="section-title">Website / brand AI check - Before vs After</div>
           ${compareMentionTable(bWeb, aWeb)}
           ${googleCompare(before, after)}`
        : ''
    }

    <div class="section-title">Ab bhi baaki kamiyan</div>
    ${gapCards(after, 5)}`;

  return pageShell('AI Visibility Before/After Report', agencyName, body);
}

// @sparticuz/chromium-min khud Chromium binary include nahi karta (isiliye chhota hai
// aur Vercel ke function-size limit mein aasani se fit hota hai). Pehli call par ye
// URL se pack.tar download karke /tmp mein extract karta hai; baad ki (warm) calls
// isi cached copy ko reuse karti hain. Version yahan aur package.json mein SAME rakho.
const CHROMIUM_PACK_URL =
  process.env.CHROMIUM_PACK_URL ||
  'https://github.com/Sparticuz/chromium/releases/download/v138.0.2/chromium-v138.0.2-pack.x64.tar';

// ---------- PDF banane wala ----------
// Har step alag se try/catch + log karte hain taaki Vercel Function Logs mein
// saaf pata chale ki crash kahan hua (chromium path, launch, ya PDF render).
export async function generatePdfBuffer(html: string): Promise<Uint8Array> {
  let executablePath: string;
  try {
    // PDF ke liye WebGL/graphics stack ki zaroorat nahi — isse off rakhne se
    // launch zyada stable rehta hai serverless (AL2023) environment mein.
    chromium.setGraphicsMode = false;
    executablePath = await chromium.executablePath(CHROMIUM_PACK_URL);
    console.log('[pdf] chromium executablePath:', executablePath);
  } catch (e) {
    console.error('[pdf] chromium.executablePath() failed:', e);
    throw new Error('Chromium binary nahi mil payi (executablePath failed)');
  }

  let browser: any;
  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath,
      headless: true,
    });
    console.log('[pdf] browser launched');
  } catch (e) {
    console.error('[pdf] puppeteer.launch() failed:', e);
    throw new Error(`Chromium launch nahi ho paya: ${e instanceof Error ? e.message : String(e)}`);
  }

  try {
    const page = await browser.newPage();
    // HTML mein koi script/external resource nahi chahiye — JS band rakhna safe hai
    await page.setJavaScriptEnabled(false);
    await page.setContent(html, { waitUntil: 'load' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' },
    });
    console.log('[pdf] pdf rendered, bytes:', pdf.length);
    return new Uint8Array(pdf);
  } catch (e) {
    console.error('[pdf] page render/pdf failed:', e);
    throw new Error(`PDF render nahi ho paya: ${e instanceof Error ? e.message : String(e)}`);
  } finally {
    try {
      await browser.close();
    } catch {
      /* ignore close errors */
    }
  }
}
